# action.yml
name: 'Diglett'
description: 'Dig for your documentation outdatedness'
inputs:
  USERNAME:
    description: 'GitHub account to access API'
    required: true
  TOKEN:
    description: 'GitHub token to access API'
    required: true
  PR_NUMBER:
    description: 'Pull request number / ID'
    required: true
  MAX_COMMITS:
    description: 'Threshold for allowed number of commits since README.md last modified, if repo has more commits'
    required: false
  MAX_DAYS:
    description: 'Threshold for allowed timedelta since README.md last modified, if repo has more commits'
    required: false
outputs:
  OutputMessage:
    description: "Output from the action"
runs:
  using: 'docker'
  image: 'Dockerfile'
