# action.yml
name: 'Diglett'
description: 'Dig for your documentation outdateness'
inputs:
  username:
    description: 'GitHub account to access API'
    required: true
  token:
    description: 'GitHub token to access API'
    required: true
  repo:
    description: 'Repo name'
    required: true
  pr_number:
    description: 'Pull request number / ID'
    required: true
  owner:
    description: 'Owner of the repo'
    required: true
  max_commits:
    description: 'Max number of commits'
    required: true
outputs:
  OutputMessage:
    description: "Output from the action"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.username }}
    - ${{ inputs.token }}
    - ${{ inputs.repo }}
    - ${{ inputs.pr_number }}
    - ${{ inputs.owner }}
    - ${{ inputs.max_commits }}
