# action.yml
name: 'Diglett'
description: 'Dig for your documentation outdateness'
inputs:
  username:
    description: 'GitHub account to access API'
    required: true
  token:
    description: 'GitHub token to access API'
    required: true
  repo:
    description: 'Repo name'
    required: true
  pr:  # id of input
    description: 'GitHub account to access API'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.username }}
    - ${{ inputs.token }}
    - ${{ inputs.owner }}
    - ${{ inputs.repo }}
    - ${{ inputs.pr }}
    - ${{ imputs.max_commits}}